### PR TITLE
feature: add password list size option and bump gem version 

### PR DESCRIPTION
**Pull request by roberttravispierce**
Updates to a newer, larger blacklist of common passwords.

### CODE REVIEW

**Comment by gchan** [comment]
Thanks for your contribution.

With a larger wordlist, we should expect a larger memory footprint, and longer processing time. 

Here are the numbers from `bin/profile` and `bin/benchmark` on your branch.

```
841.74 kB allocated on 95k wordlist
2.83 MB allocated on 304k wordlist (~3.36x more)

2110.9 i/s on 95k wordlist
613.7 i/s on 304 wordlist (~3.44x slower).
```

These numbers remain satisfactory to me, however it might be worth updating the README to indicate the new memory footprint from 0.8 MB to 2.8 MB (as this may affect people's use cases).

**Comment by roberttravispierce** [comment]
Thanks. I've updated the README. I’d like to work on an option to select the size/footprint of wordlist when calling the gem. e.g. `PasswordBlacklist.blacklisted?(password, small)` if you think that would be useful.

**Comment by gchan** [comment]
Thanks @roberttravispierce ! 

It could be useful to use a smaller wordlist by default and have the option to select the larger wordlist. That way we maintain similar performance as before but provide the option for others to use the larger wordlist if they wish.

Perhaps something like `PasswordBlacklist.blacklisted?(password, large_worldlist)` ? 
The default parameter of `large_wordlist` could be false such that `PasswordBlacklist.blacklisted?(password)` still works.

In terms of a smaller wordlist, maybe we could use the original 95k file or perhaps use a truncated version of the 304k file (perhaps take only the first 95k lines?). 

Let me know what you think.

**Comment by roberttravispierce** [comment]
Ok, I've pushed the select password list size option. Let me know if you have any issues with it. I kept the original 95k list as the default.

**Comment by gchan** [comment]
Thanks for your patience @roberttravispierce. Your changes look good to me, and I'm happy to merge this PR.

There are a few small things I would like to add/change but I feel it wouldn't be fair to request more changes from you.

With the ability to select the wordlist size, I noticed there is a performance regression when using testing multiple passwords against a [stored list in memory](https://github.com/gchan/password_blacklist#test-multiple-passwords). Based on the benchmarks, the performance have approximately been halved. I feel bulk testing of passwords is likely to be an uncommon use case of this library so it can be improved later.

Let me know if you want to continue working on this otherwise I will merge it in a couple of days.
Thanks again for your contribution! 🙌

**Comment by gchan** [comment]
Thanks you again @roberttravispierce for your contribution.

I've released your feature as v0.5.0 in [password_blocklist](https://rubygems.org/gems/password_blocklist).  🎉

Please note the rename of the library.

**Pull request merged**
